export const items =[
    {
        id:"1",
        category:"Client Projects",
        title:"BookMyTowing",
        description:"Street2Site transformed BookMyTowing's outdated website into a modern, user-friendly platform. We enhanced navigation, implemented responsive design, and streamlined the booking process, allowing users to request towing assistance effortlessly. This transformation improved their online presence, reflecting their commitment to reliability and significantly boosting user engagement.",
        image:'/assets/Works/Myworks/w2.jpg',
        role:"Design and Development",
        collabors:["Mahesh","Rupesh","Salludeen","Kishan"],
    },
    {
        id:"2",
        category:"Client Projects",
        title:"Tejas Digital Studio",
        description:"Tejas Digital Studio revitalized BookMyTowing’s online presence with a sleek, user-focused website redesign. We upgraded navigation, added responsive design elements, and optimized the booking process, making it easy for customers to request towing services with just a few clicks. This overhaul reinforced their brand's reliability and significantly increased user engagement, reflecting their dedication to superior service.",
        image:'/assets/Works/Myworks/w3.jpg',
        role:"Design and Development",
        collabors:["Kishan"],
    },
    {
        id:"3",
        category:"Client Projects",
        title:"Microcomonline",
        description:"Microcomonline White, a forward-thinking startup, entrusted us with the development of their website, tailored specifically for their international clientele. We focused on creating an innovative online platform that caters to diverse global needs, ensuring seamless interactions and high-quality service. Our commitment to excellence in this project has positioned us as a reliable partner in the international market, driving engagement and fostering long-term relationships with clients worldwide.",
        image:'/assets/Works/Myworks/w4.jpg',
        role:"Design and Development",
        collabors:["Kishan"],
    },
    {
        id:"4",
        category:"Personal Projects",
        title:"Street2site",
        description:"Street2Site is a freelancing company founded by friends dedicated to elevating businesses into the digital realm. We provide a comprehensive range of services, including web design, SEO, UI/UX design, and success solutions. Our mission is to empower businesses by creating stunning online presences that drive growth and engagement. With a passionate team of experts, Street2Site transforms your vision into reality, helping you thrive in the competitive digital landscape. Let us partner with you to take your business to new heights!",
        image:'/assets/Works/Myworks/w1.jpg',
        role:"Design and Development",
        collabors:["Kishan"],
    },
    {
        id:"5",
        category:"Personal Projects",
        title:"Youtube Clone",
        description:"The YouTube Clone is a responsive web application built with React that leverages the YouTube Data API to fetch videos based on categories. It features a sleek dark mode for comfortable viewing in low-light environments. Users can easily browse through different categories, play videos in an embedded player, and enjoy a user-friendly interface that adapts seamlessly across various devices. This project highlights the integration of API data, offering an engaging video streaming experience while ensuring accessibility and aesthetic appeal.",
        image:'/assets/Works/Myworks/w5.jpg',
        role:"Design and Development",
    },
    {
        id:"6",
        category:"Personal Projects",
        title:"Real-Time Map Tracking Feature",
        description:"With our real-time map tracking feature, users can view their current location and easily click anywhere on the map to generate a route. If friends join via a shared link, everyone can see each other’s locations and routes in real-time, enhancing collaboration and navigation during group outings or events.",
        image:'/assets/Works/Myworks/w6.jpg',
        role:"Design and Development",
    },
    {
        id:"7",
        category:"Client Projects",
        title:"AI Bot Pdf Reader",
        description:"With our real-time map tracking feature, users can view their current location and easily click anywhere on the map to generate a route. If friends join via a shared link, everyone can see each other’s locations and routes in real-time, enhancing collaboration and navigation during group outings or events.",
        image:'/assets/Works/Myworks/w7.jpg',
        role:"Design and Development",
        collabors:["Kishan","Lavanya M"],
    },
    {
        id:"8",
        category:"Client Projects",
        title:"Skin Disease Prediction (Patient side)",
        description:"Our skin disease prediction website provides a seamless experience for users to consult with doctors and manage their health. Users can easily register or log in to upload images of skin conditions, receive detailed insights, and connect with available doctors for expert consultations. Doctors can log in to access a personalized dashboard where they can review patient details, send prescriptions, and analyze trends through a five-year graph of skin disease data. This system ensures efficient, data-driven healthcare delivery while keeping both patients and doctors informed about current skin disease patterns",
        image:'/assets/Works/Myworks/w8.jpg',
        role:"Design and Development",
        collabors:["Kishan","Lavanya M"],
    },
    {
        id:"9",
        category:"Client Projects",
        title:"Skin Disease Prediction (Doctor Side)",
        description:"Our skin disease prediction website provides a seamless experience for users to consult with doctors and manage their health. Users can easily register or log in to upload images of skin conditions, receive detailed insights, and connect with available doctors for expert consultations. Doctors can log in to access a personalized dashboard where they can review patient details, send prescriptions, and analyze trends through a five-year graph of skin disease data. This system ensures efficient, data-driven healthcare delivery while keeping both patients and doctors informed about current skin disease patterns",
        image:'/assets/Works/Myworks/w9.jpg',
        role:"Design and Development",
        collabors:["Kishan","Lavanya M"],
    },
    {
        id:"10",
        category:"Personal Projects",
        title:"Telegram Anti Drug Free Bot ",
        description:"Our Telegram bot offers an innovative approach to monitoring and addressing drug-related activities in group chats. The bot actively detects drug-related keywords in user messages, requests the user's location, and securely stores crucial details like username, chat ID, group name, text content, and location in a database. This system enables administrators to monitor group activities effectively, promoting a safer and more accountable environment. With its seamless integration and real-time data handling, the bot provides a powerful tool for community management and awareness.",
        image:'/assets/Works/Myworks/w10.jpg',
        role:"Design and Development",
        collabors:["Kishan","Naveen"],
    },
    {
        id:"11",
        category:"Client Projects",
        title:"IoT-based landslide detection system",
        description:"Our Telegram bot offers an innovative approach to monitoring and addressing drug-related activities in group chats. The bot actively detects drug-related keywords in user messages, requests the user's location, and securely stores crucial details like username, chat ID, group name, text content, and location in a database. This system enables administrators to monitor group activities effectively, promoting a safer and more accountable environment. With its seamless integration and real-time data handling, the bot provides a powerful tool for community management and awareness.",
        image:'/assets/Works/Myworks/w11.jpg',
        role:"Design and Development",
        collabors:["Kishan","Sanjay","Yashwin","Naveen"],
    },
    {
        id:"12",
        category:"others",
        title:"IoT-based Smart Irrigation System",
        description:"Our IoT-based smart irrigation system offers a modern solution for efficient water management in agriculture. Powered by an Arduino Uno, the system utilizes soil moisture sensors, temperature sensors, and a rain gauge to monitor environmental conditions in real time. It automates irrigation by activating water flow only when needed, reducing water waste and ensuring healthy crop growth. An LCD screen provides real-time updates, making the system simple to use and highly effective for sustainable farming.",
        image:'/assets/Works/Myworks/w12.jpg',
        role:"Design and Development",
        collabors:["Kishan","Mahesh","Rupesh"],
    },
]


export const categories = ["Client Projects", "Personal Projects","others"]